name: Package and create artifact
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  alpha:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Package
        uses: BigWigsMods/packager@master
        with:
          args: -z

      - name: Get short commit sha
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: LibDropDown-${{ steps.sha.outputs.sha_short }}
          path: .release/
