name: Generate docs
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Clone wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: .wiki

      - name: Parse and generate docs
        uses: p3lim/lua-doc-parser@v2
        with:
          output: .wiki

      - name: Push docs
        run: |
          cd .wiki
          git config user.name CI
          git config user.email "<>"
          git add .
          git diff --quiet HEAD || git commit -m "$GITHUB_SHA"
          git push
